LOCATION_TYPES = {
    "continent": ["continent"],
    "country": ["country"],
    "country_code": ["country_code"],
    "region": ["state", "county", "region", "state_district"],
    "city": [
        "city",
        "town",
        "village",
        "municipality",
        "city_district",
        "district",
        "borough",
        "suburb",
        "subdivision",
        "hamlet",
        "croft",
        "isolated_dwelling",
    ],
    "road": [
        "road",
        "neighbourhood",
        "allotments",
        "quarter",
        "city_block",
        "residential",
        "farm",
        "farmyard",
        "industrial",
        "commercial",
        "retail",
    ],
    "house_id": ["house_number", "house_name"],
    "typo": [
        "emergency",
        "historic",
        "military",
        "natural",
        "landuse",
        "place",
        "railway",
        "man_made",
        "aerialway",
        "boundary",
        "amenity",
        "aeroway",
        "club",
        "craft",
        "leisure",
        "office",
        "mountain_pass",
        "shop",
        "tourism",
        "bridge",
        "tunnel",
        "waterway",
    ],
    "postcode": ["postcode"],
}
